vich_uploader:
  db_driver: orm

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'

  mappings:
    application_images_upload:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      directory_namer:
        service: vich_uploader.namer_directory_property
        options: { property: 'developer.id', transliterate: true }
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true





    application_executables_upload:
      uri_prefix: uploads/files
      upload_destination: '%kernel.project_dir%/public/uploads/files'
      directory_namer:
        service: vich_uploader.namer_directory_property
        options: { property: 'app.id', transliterate: true }
      namer:
        service: vich_uploader.namer_property
        options: { property: 'app.slug', transliterate: true }

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true